// swift-tools-version:5.9
import PackageDescription

// HopDriver, the reusable Apple driver for the Hop runtime (north-star drivers/apple location).
//
// It owns the whole Hop bearer (BLE/Wi-Fi/LAN/relay transports + the node) so a host app
// is a thin consumer. Multiplatform: iOS 16 (the demo app) + macOS 13 (the `hopmac` headless
// BLE-central test node). The generated FFI bindings + the prebuilt xcframework live inside the
// package (regenerated by tools/build-xcframework.sh); both are gitignored build artifacts.
let package = Package(
    name: "HopDriver",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "HopDriver", targets: ["HopDriver"]),
        .executable(name: "hopmac", targets: ["hopmac"]),
        .executable(name: "relaymac", targets: ["relaymac"]),
    ],
    // The transport layer is the four INDEPENDENT bearer packages (bearers/apple/*), each binding the
    // pure-Swift HopContract (from sdk/apple). BLE + LAN + cloud relay links now form ONLY through
    // those bearers via the BearerManager (there is no `Config.useSharedBearers` flag and no in-driver
    // HopLink/GattDataLink/LanLink fallback, those were deleted in the cutover). Multipeer (Wi-Fi P2P)
    // and the direct hops:// endpoints remain in-driver; the long-lived IOThread is retained purely as the
    // shared BLE runloop the BleBearer schedules its L2CAP streams + timers on. The old apple/HopBearers
    // package is gone.
    dependencies: [
        // The node API stays on UniFFI (HopFFI.xcframework). The bearers are now the INDEPENDENT
        // packages, binding HopContract (pure Swift, no libhop), so no double-link of the Rust core.
        .package(path: "../../../sdk/apple"),
        .package(path: "../../../bearers/apple/HopBearerBle"),
        .package(path: "../../../bearers/apple/HopBearerLan"),
        .package(path: "../../../bearers/apple/HopBearerRelay"),
    ],
    targets: [
        // The Rust core, compiled to a static lib and packaged as an xcframework (ios-arm64,
        // ios-sim, macos). Built by tools/build-xcframework.sh.
        .binaryTarget(name: "hopFFI", path: "Frameworks/HopFFI.xcframework"),

        // The Objective-C exception catcher (CoreBluetooth raises NSExceptions Swift can't catch).
        // A Clang target with an include/ umbrella header; replaces the app's bridging header.
        .target(name: "HopObjC"),

        // The UniFFI-generated Swift API (hop.swift), which imports the binary module.
        .target(name: "HopFFIBindings", dependencies: ["hopFFI"]),

        // The bearer + transports.
        .target(name: "HopDriver", dependencies: [
            "HopFFIBindings", "HopObjC",
            .product(name: "HopContract",    package: "apple"),
            .product(name: "HopBearerBle",   package: "HopBearerBle"),
            .product(name: "HopBearerLan",   package: "HopBearerLan"),
            .product(name: "HopBearerRelay", package: "HopBearerRelay"),
        ]),

        // Headless macOS BLE-central node driving the driver in `.centralOnly` mode.
        .executableTarget(name: "hopmac", dependencies: ["HopDriver"]),
        // Headless macOS RELAY-ONLY client (`.relayOnly` mode), no BLE/LAN/Wi-Fi, relay path only.
        .executableTarget(name: "relaymac", dependencies: ["HopDriver"]),

        // sec-priv-02: the Keychain-backed identity/db-key store, tested headlessly on macOS (the
        // generic-password path works without a device; SE wrapping no-ops when the Enclave is absent).
        .testTarget(name: "HopDriverTests", dependencies: ["HopDriver"]),
    ]
)
